spring:
  application:
    name: SampleWeChat

mvf4ms:
  version: 2.0.0
  dependencies:
    - name: dependency1
      dependence:
        - id: weather
          serviceName: SampleCNWeather
          patternUrl: /weather
          versions:
            - 2.1.0
        - id: PDelivery
          function: PDelivery
          slas:
            - 2
            - 4

server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://{REGISTRY_IP}:{REGISTRY_PORT}/eureka
